baseURL = 'https://hungngocphat01.github.io/'
languageCode = 'en-us'

theme = "LoveIt"


[params]
# site default theme ["auto", "light", "dark"]
# 网站默认主题 ["auto", "light", "dark"]
defaultTheme = "light"
# public git repo url only then enableGitInfo is true
# 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
gitRepo = ""
# which hash function used for SRI, when empty, no SRI is used
# ["sha256", "sha384", "sha512", "md5"]
# 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
# ["sha256", "sha384", "sha512", "md5"]
fingerprint = ""
# date format
# 日期格式
dateFormat = "2006-01-02"
# website title for Open Graph and Twitter Cards
# 网站标题, 用于 Open Graph 和 Twitter Cards
title = "~/hiraki"
# website description for RSS, SEO, Open Graph and Twitter Cards
# 网站描述, 用于 RSS, SEO, Open Graph 和 Twitter Cards
description = "hiraki's blog"
# website images for Open Graph and Twitter Cards
# 网站图片, 用于 Open Graph 和 Twitter Cards
images = []

# Author config
# 作者配置
[params.author]
name = "hiraki"

# Header config
# 页面头部导航栏配置
[params.header]
# desktop header mode ["fixed", "normal", "auto"]
# 桌面端导航栏模式 ["fixed", "normal", "auto"]
desktopMode = "fixed"
# mobile header mode ["fixed", "normal", "auto"]
# 移动端导航栏模式 ["fixed", "normal", "auto"]
mobileMode = "auto"
# Header title config
# 页面头部导航栏标题配置
[params.header.title]
# URL of the LOGO
# LOGO 的 URL
logo = ""
# title name
# 标题名称
name = "~/hiraki"
# you can add extra information before the name (HTML format is supported), such as icons
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
# whether to use typeit animation for title name
# 是否为标题显示打字机动画
typeit = false

[params.footer]
enable = true
# Custom content (HTML format is supported)
# 自定义内容 (支持 HTML 格式)
custom = ""
# whether to show Hugo and theme info
# 是否显示 Hugo 和主题信息
hugo = false
# whether to show copyright info
# 是否显示版权信息
copyright = true
# whether to show the author
# 是否显示作者
author = true
# site creation time
# 网站创立年份
since = 2019
# license info (HTML format is supported)
# 许可协议信息 (支持 HTML 格式)
license = ""

[params.app]
# optional site title override for the app when added to an iOS home screen or Android launcher
# 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题

title = "~/hiraki"
[params.home]

# amount of RSS pages
# RSS 文章数目
rss = 10
# Home page profile
# 主页个人信息
[params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = ""
# URL of avatar shown in home page
# 主页显示头像的 URL
avatarURL = ""
# title shown in home page (HTML format is supported)
# 主页显示的网站标题 (支持 HTML 格式)
title = "hungngocphat01"
# subtitle shown in home page (HTML format is supported)
# 主页显示的网站副标题 (允许 HTML 格式)
subtitle = "Researcher. Engineer. Wibu"
# whether to use typeit animation for subtitle
# 是否为副标题显示打字机动画
typeit = true
# whether to show social links
# 是否显示社交账号
social = true
# disclaimer (HTML format is supported)
# 免责声明 (支持 HTML 格式)
disclaimer = ""
# Home page posts
# 主页文章列表
[params.home.posts]
enable = true
# special amount of posts in each home posts page
# 主页每页显示文章数量
paginate = 6

[params.social]
GitHub = "hungngocphat01"
Linkedin = "hungngocphat-hcmus"

[params.page]
[params.page.math]
enable = true

[params.page.seo]
# image URL
images = []
[params.page.seo.publisher]
name = "hiraki"
logoUrl = "img/hcmus-logo-white.png"

[params.seo]
image = "img/hcmus-logo-white.png"

[params.analytics]
enable = true
# Google Analytics
[params.analytics.google]
id = "G-B4947G4B6F"
anonymizeIP = true

[markup]
[markup.highlight]
style = "github"
lineNos = true
lineNumbersInTable = true
noClasses = false

[menu]
[[menu.main]]
weight = 2
identifier = "posts"
name = "Posts"
url = "/posts/"

[[menu.main]]
weight = 1
identifier = "whoami"
name = "About"
url = "/whoami/"

[[menu.main]]
weight = 3
identifier = "tags"
name = "Tags"
url = "/tags/"

[[menu.main]]
weight = 3
identifier = "projects"
name = "Personal projects"
url = "/projects/"

[[menu.main]]
weight = 4
name = "Old site"
url = "/old/"

[markup.goldmark.renderer]
unsafe = true

[caches]
[caches.images]
dir = ':cacheDir/images'
